### ISSUE TITLE
Add Project Structure for Chunked Model Loader

### ISSUE THREAD

**Issue by Adarshreddyash** [Adarshreddyash/surfing#1]
## Files to Add

The following files and directories will be added to the repository:

```
surfing/
├── .github/
│   ├── ISSUE_TEMPLATE/
│   │   ├── bug_report.md
│   │   └── feature_request.md
│   └── workflows/
│       ├── ci.yml
│       ├── publish.yml
│       └── docs.yml
├── src/
│   └── chunked_model_loader/
│       ├── __init__.py
│       ├── storage/
│       │   ├── __init__.py
│       │   ├── base.py
│       │   ├── s3.py
│       │   ├── http.py
│       │   └── p2p.py
│       ├── cache/
│       │   ├── __init__.py
│       │   ├── lru.py
│       │   └── metrics.py
│       ├── adapters/
│       │   ├── __init__.py
│       │   ├── lora.py
│       │   ├── peft.py
│       │   └── huggingface.py
│       ├── monitoring/
│       │   ├── __init__.py
│       │   ├── collectors.py
│       │   └── exporters.py
│       ├── optimization/
│       │   ├── __init__.py
│       │   ├── profiler.py
│       │   └── strategies.py
│       ├── config/
│       │   ├── __init__.py
│       │   └── loader_config.py
│       └── utils/
│           ├── __init__.py
│           └── chunking.py
├── tests/
│   ├── __init__.py
│   ├── conftest.py
│   ├── unit/
│   │   ├── __init__.py
│   │   ├── test_storage.py
│   │   ├── test_cache.py
│   │   └── test_adapters.py
│   ├── integration/
│   │   ├── __init__.py
│   │   └── test_full_pipeline.py
│   └── performance/
│       ├── __init__.py
│       └── test_benchmarks.py
├── docs/
│   ├── source/
│   │   ├── conf.py
│   │   ├── index.rst
│   │   ├── api/
│   │   ├── guides/
│   │   └── examples/
│   └── Makefile
├── examples/
│   ├── fastapi_service/
│   ├── edge_device_demo/
│   ├── multi_model_chat/
│   └── model_hub_server/
├── scripts/
│   ├── chunk_model.py
│   ├── validate_chunks.py
│   └── benchmark.py
├── .gitignore
├── .pre-commit-config.yaml
├── pyproject.toml
├── Dockerfile
├── docker-compose.yml
└── Makefile
```

### pyproject.toml
```toml
[project]
name = "chunked-model-loader"
version = "0.1.0"
description = "A scalable, memory-efficient way to load large AI models"
requires-python = ">=3.8"
authors = [
    {name = "Adarsh", email = "adarshreddy9849@gmail.com"},
]
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "aiobotocore>=2.5.0",
    "aiohttp>=3.8.0",
    "pydantic>=2.0.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "hypothesis>=6.75.3",
]
docs = [
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=1.2.0",
    "myst-parser>=2.0.0",
]
dev = [
    "black>=23.3.0",
    "isort>=5.12.0",
    "ruff>=0.0.270",
    "mypy>=1.3.0",
    "pre-commit>=3.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
select = ["E", "F", "B"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.8"
strict = true
```

### .pre-commit-config.yaml
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff
```

### Makefile
```makefile
.PHONY: install test lint format docs clean

install:
  pip install -e ".[dev,test,docs]"
  pre-commit install

test:
  pytest tests/ --cov=chunked_model_loader --cov-report=xml

lint:
  ruff check .
  black --check .
  isort --check .
  mypy src/

format:
  black .
  isort .

docs:
  cd docs && make html

clean:
  rm -rf build/
  rm -rf dist/
  rm -rf *.egg-info
  rm -rf .pytest_cache
  rm -rf .coverage
  rm -rf coverage.xml
  find . -type d -name "__pycache__" -exec rm -rf {} +
```

## Implementation Steps

1. Create the directory structure
2. Add configuration files
3. Add placeholder files for each module
4. Set up initial CI/CD workflows
5. Update README.md with project description and setup instructions

## Note
- Existing LICENSE and README.md files will be preserved
- All new files will be added with appropriate structure and initial content
- GitHub Actions workflows will be set up for CI/CD
- Documentation will be configured with Sphinx

Would you like me to proceed with implementing this structure in the main branch?
